# Generated by Django 5.0.4 on 2024-04-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(blank=True, max_length=255, null=True)),
                ('make', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.IntegerField(default=0)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'items',
            },
        ),
    ]
