# Generated by Django 5.0.4 on 2024-05-01 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Djangopro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectname', models.CharField(blank=True, max_length=255, null=True)),
                ('nechanchiproject', models.IntegerField(default=10)),
            ],
            options={
                'db_table': 'finally',
            },
        ),
        migrations.CreateModel(
            name='Finallypro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oxirgisimi', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'project',
            },
        ),
    ]
