# Generated by Django 5.0.4 on 2024-04-30 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolnumber', models.IntegerField(default=1)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('student', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'school',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameuni', models.CharField(blank=True, max_length=255, null=True)),
                ('courses', models.CharField(blank=True, max_length=255, null=True)),
                ('student', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'university',
            },
        ),
    ]
