# Generated by Django 5.0.4 on 2024-04-30 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurs', models.CharField(blank=True, max_length=255, null=True)),
                ('oyliktulov', models.IntegerField(default=50000)),
            ],
            options={
                'db_table': 'edu',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('kurs', models.CharField(blank=True, max_length=255, null=True)),
                ('sallery', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'teachers',
            },
        ),
    ]
