# Generated by Django 5.0.4 on 2024-04-30 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rejjissor', models.CharField(blank=True, max_length=255, null=True)),
                ('sennerist', models.CharField(blank=True, max_length=255, null=True)),
                ('namemovie', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'kinolar',
            },
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('namemusic', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'musics',
            },
        ),
    ]
